### ISSUE TITLE
The solution of task you submitted was incorrect.

### ISSUE THREAD

**Issue by ManuCortex** [FunCaptcha/funcaptcha-joomla#1]
I´m using Funcaptcha plugin for joomla in my website. When someone send a form with the capcha displays the message: The solution of task you submitted was incorrect. Please read the instruction and try again. My website is: http://mineclack.com

You can see the issue here: http://mineclack.com/index.php/component/users/?view=reset

Is there any solution?

**Comment by kgosschalk** [comment]
Hi ManuCortex,

Thanks for reaching out. We've figured out how to resolve this issue for you and we're going to email it through to you.

Kind regards,
Kevin
